
-- هذا التريجر لا يسمح بتخصيص فرق مشغولة في كارثه اخرى او ان الكارثه قد انتهت 

CREATE OR REPLACE TRIGGER TRG_CHECK_TEAMS_ASSIGNMENT
BEFORE INSERT OR UPDATE ON TEAM_ASSIGNMENT
FOR EACH ROW
DECLARE
DIS_STATUS VARCHAR2(20);
TEAM_STATUS VARCHAR2(20);
BEGIN
SELECT DIS.STATUS INTO DIS_STATUS FROM DISASTERS DIS WHERE DIS.DISASTER_ID = :NEW.DISASTER_ID;
IF DIS_STATUS = 'انتهت' THEN
RAISE_APPLICATION_ERROR(-20001,'لا يمكن تخصيص فريق لكارثة منتهية');
END IF;
SELECT T.STATUS INTO TEAM_STATUS FROM TEAMS T WHERE T.TEAM_ID = :NEW.TEAM_ID;
IF TEAM_STATUS = 'نشط' THEN
RAISE_APPLICATION_ERROR(-20002,'الفريق مشغول في كارثةاخرى');
END IF;
END; 
/
