CREATE OR REPLACE TRIGGER TRG_UPDATE_DISASTER_STATUS
BEFORE  INSERT OR UPDATE OF END_TIME ON DISASTERS
FOR EACH ROW
BEGIN
IF :NEW.END_TIME IS NOT NULL THEN
:NEW.STATUS := 'انتهت';
ELSE
:NEW.STATUS := 'لا تزال فعالة';
END IF;
END;

