SET SERVEROUTPUT ON SIZE UNLIMITED;


-- هذا الاستعلام يعرض اسماء الكوارث و اسم الموقع و حالة الكارثة
SELECT DIS.NAME AS "NAME DISASTER", LOC.NAME AS "DISASTER LOCATION", DIS.STATUS AS "DISASTER STATUS" 
FROM DISASTERS DIS INNER JOIN LOCATIONS LOC
ON DIS.DISASTER_ID = LOC.DISASTER_ID;

--  هنا تنفيذ للدوال الموجودة في الحزمة والتي تعرض 
-- عدد الفرق المشاركة في كارثه معينه و عدد الضحايا المتأثرة في كارثة معينه 
BEGIN
DBMS_OUTPUT.PUT_LINE(COUNT_VICTIMS_AND_TEAMS.COUNT_TEAMS(1));
DBMS_OUTPUT.PUT_LINE(COUNT_VICTIMS_AND_TEAMS.COUNT_VICTIMS(1));
END;

-- هذا الاستعلام يعرض اسم الكارثة و اسم الفريق المخصص لها و دور الفريق و زمن التخصيص  من ثلاثه جداول
SELECT DIS.NAME AS "DISASTER NAME", T.NAME AS "TEAM NAME", ASS.ROLE AS "TEAM ROLE", ASS.ASSIGNED_AT AS "ASSIGNMENT TIME"
FROM DISASTERS DIS INNER JOIN TEAM_ASSIGNMENT ASS
ON DIS.DISASTER_ID = ASS.DISASTER_ID INNER JOIN TEAMS T
ON ASS.TEAM_ID = T.TEAM_ID;

-- هذا الاستعلام يعرض اكثر الفرق مشاركة في الكوارث
SELECT T.NAME, COUNT(ASS.ASSIGNMENT_ID) AS ASSIGNMENT_COUNT FROM
TEAMS T JOIN TEAM_ASSIGNMENT ASS
ON T.TEAM_ID = ASS.TEAM_ID
GROUP BY T.NAME
HAVING COUNT(ASS.ASSIGNMENT_ID) > 0
ORDER BY ASSIGNMENT_COUNT DESC;
