-- هذه الحزمه تحتوي على دالتين تسرعان عملية الاستعلام 
CREATE OR REPLACE PACKAGE COUNT_VICTIMS_AND_TEAMS AS
FUNCTION COUNT_VICTIMS (P_DISASTER_ID NUMBER) RETURN NUMBER;
FUNCTION COUNT_TEAMS(P_DISASTER_ID NUMBER) RETURN NUMBER;
END COUNT_VICTIMS_AND_TEAMS;

CREATE OR REPLACE PACKAGE BODY COUNT_VICTIMS_AND_TEAMS AS
-- THIS FUNCTION SHOW THE VICTIMS NUMBER OF ANY DISASTER
FUNCTION COUNT_VICTIMS (P_DISASTER_ID NUMBER) RETURN NUMBER IS
VICTIM_COUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO VICTIM_COUNT FROM VICTIMS WHERE DISASTER_ID = P_DISASTER_ID;
RETURN VICTIM_COUNT;
END;
-- THIS FUNCTION SHOW THE TEAMS NUMBER ASSIGNED FOR ANY DISASTER
FUNCTION COUNT_TEAMS(P_DISASTER_ID NUMBER) RETURN NUMBER IS
TEAM_COUNT NUMBER;
BEGIN
SELECT COUNT(*) INTO TEAM_COUNT FROM TEAM_ASSIGNMENT WHERE DISASTER_ID = P_DISASTER_ID;
RETURN TEAM_COUNT;
END;
END COUNT_VICTIMS_AND_TEAMS;
