-- انشا مستخدم و منحه الصالحيات اللازمه 
CREATE TABLESPACE DISASTERS_DATA
DATAFILE 'DISASTERS_DATA.dbf' SIZE 100M AUTOEXTEND ON;

CREATE USER DISASTERS_MANGEMENT IDENTIFIED BY DIS000
DEFAULT TABLESPACE DISASTERS_DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DISASTERS_DATA;

GRANT CONNECT, RESOURCE TO DISASTERS_MANGEMENT;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO DISASTERS_MANGEMENT;

CONN DISASTERS_MANGEMENT;