
-- انشاء الجداول و ربطها ببعضها 
CREATE TABLE DISASTERS (
DISASTER_ID INTEGER ,
NAME VARCHAR2(150) NOT NULL,
TYPE VARCHAR2(50) NOT NULL,
DESCRIPTION VARCHAR2(4000),
START_TIME TIMESTAMP NOT NULL,
END_TIME TIMESTAMP,
STATUS VARCHAR2(20),
CONSTRAINT DISASTERS_DISASTERID_PK PRIMARY KEY (DISASTER_ID)
);


CREATE TABLE LOCATIONS (
LOCATION_ID INTEGER ,
NAME VARCHAR2(150) NOT NULL,
DESCRIPTION VARCHAR2(4000),
TYPE VARCHAR2(30),
CREATED_AT TIMESTAMP,
DISASTER_ID INTEGER,
CONSTRAINT LOCATION_LOCATIONID_PK PRIMARY KEY (LOCATION_ID),
CONSTRAINT LOCATION_DISASTERID_FK FOREIGN KEY (DISASTER_ID) REFERENCES DISASTERS(DISASTER_ID)
);


CREATE TABLE VICTIMS (
VICTIM_ID INTEGER ,
NAME VARCHAR2(150),
AGE INTEGER CHECK(AGE>0),
GENDER VARCHAR2(20) NOT NULL,
TRIAGE_LEVEL INTEGER,
CONDITION VARCHAR2(1000),
CREATED_AT TIMESTAMP,
DISASTER_ID INTEGER,
LOCATION_ID INTEGER,
CONSTRAINT VICTIMS_VICTIMID_PK PRIMARY KEY (VICTIM_ID),
CONSTRAINT VICTIMS_LOCATIONID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID),
CONSTRAINT VICTIMS_DISASTERID_FK FOREIGN KEY (DISASTER_ID) REFERENCES DISASTERS(DISASTER_ID)
);


CREATE TABLE TEAMS(
TEAM_ID INTEGER,
NAME VARCHAR2(150) NOT NULL,
TYPE VARCHAR2(30) NOT NULL,
STATUS VARCHAR2(20),
CAPACITY INTEGER NOT NULL,
BASE_LOCATION_ID INTEGER,
CONSTRAINT TEAMS_TEAMID_PK PRIMARY KEY (TEAM_ID),
CONSTRAINT TEAMS_BASELOCATIONID_FK FOREIGN KEY (BASE_LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

-- انشاء فهرس لتسريع عملية الاستعلامات على جدول الفرق 
CREATE INDEX STATUS_INDEX ON TEAMS(STATUS);
CREATE INDEX BASE_LOCATION_ID_INDEX ON TEAMS(BASE_LOCATION_ID);

CREATE TABLE TEAM_CONTACT_PHONE (
CONTACT_ID INTEGER,
CONTACT_PHONE VARCHAR2(12) NOT NULL,
TEAM_ID INTEGER,
CONSTRAINT TEAMCONTACTPHONE_CONTACTID_PK PRIMARY KEY (CONTACT_ID),
CONSTRAINT TEAMCONTACTPHONE_TEAMID_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(TEAM_ID)
);


CREATE TABLE TEAM_CONTACT_EMAIL (
EMAIL_ID INTEGER,
CONTACT_EMAIL VARCHAR2(100) NOT NULL,
TEAM_ID INTEGER,
CONSTRAINT TEAMCONTACTEMAIL_EMAILID_PK PRIMARY KEY (EMAIL_ID),
CONSTRAINT TEAMCONTACTEMAIL_TEAMID_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(TEAM_ID)
);


CREATE TABLE TEAM_ASSIGNMENT (
ASSIGNMENT_ID INTEGER,
ROLE VARCHAR2(1000),
ASSIGNED_AT TIMESTAMP,
RELEASED_AT TIMESTAMP,
NOTE VARCHAR2(4000),
DISASTER_ID INTEGER NOT NULL,
TEAM_ID INTEGER NOT NULL,
CONSTRAINT TEAMASSIGNMENT_ASSIGNMENTID_PK PRIMARY KEY (ASSIGNMENT_ID),
CONSTRAINT TEAMASSIGNMENT_DISASTERID_FK FOREIGN KEY (DISASTER_ID) REFERENCES DISASTERS(DISASTER_ID),
CONSTRAINT TEAMASSIGNMENT_TEAMID_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID)
);

CREATE TABLE EQUIPMENT (
EQUIPMENT_ID INTEGER,
NAME VARCHAR2(150) NOT NULL,
TYPE VARCHAR2(30),
SERIAL_NUMBER VARCHAR2(20) UNIQUE,
STATUS VARCHAR2(20) NOT NULL,
LAST_MAINTENANCE VARCHAR2(50),
TEAM_ID INTEGER,
CONSTRAINT EQUIPMENT_EQUIPMENTID_PK PRIMARY KEY(EQUIPMENT_ID),
CONSTRAINT EQUIPMENT_TEAMID_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(TEAM_ID)
);
