-- انشاء التسلسلات لكل جدول في المستخدم الجديد
CREATE SEQUENCE DISASTERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LOCATIONS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VICTIMS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TEAMS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TEAM_CONTACT_PHONE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TEAM_CONTACT_EMAIL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TEAM_ASSIGNMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EQUIPMENT_SEQ START WITH 1 INCREMENT BY 1;


-- انشاء التريجرات التي تربط التسلسلات بالجداول لتتم عملية اضافة المفاتيح الاساسية تلقائيا
CREATE OR REPLACE TRIGGER TRG_DISASTERS BEFORE
    INSERT ON DISASTERS
     FOR EACH ROW
BEGIN
  SELECT DISASTERS_SEQ.NEXTVAL INTO :NEW.DISASTER_ID FROM DUAL;
END;
 

CREATE OR REPLACE TRIGGER TRG_LOCATIONS BEFORE
    INSERT ON LOCATIONS
     FOR EACH ROW
BEGIN
  SELECT LOCATIONS_SEQ.NEXTVAL INTO :NEW.LOCATION_ID FROM DUAL;
END;


CREATE OR REPLACE TRIGGER TRG_TEAMS BEFORE
    INSERT ON TEAMS
     FOR EACH ROW
BEGIN
  SELECT TEAMS_SEQ.NEXTVAL INTO :NEW.TEAM_ID FROM DUAL;
END;


CREATE OR REPLACE TRIGGER TRG_TEAM_CONTACT_PHONE BEFORE
    INSERT ON TEAM_CONTACT_PHONE
     FOR EACH ROW
BEGIN
  SELECT TEAM_CONTACT_PHONE_SEQ.NEXTVAL INTO :NEW.CONTACT_ID FROM DUAL;
END;


CREATE OR REPLACE TRIGGER TRG_TEAM_CONTACT_EMAIL BEFORE
    INSERT ON TEAM_CONTACT_EMAIL
     FOR EACH ROW
BEGIN
  SELECT TEAM_CONTACT_EMAIL_SEQ.NEXTVAL INTO :NEW.EMAIL_ID FROM DUAL;
END;



CREATE OR REPLACE TRIGGER TRG_VICTIM BEFORE
    INSERT ON VICTIMS
     FOR EACH ROW
BEGIN
  SELECT VICTIMS_SEQ.NEXTVAL INTO :NEW.VICTIM_ID FROM DUAL;
END;


CREATE OR REPLACE TRIGGER TRG_TEAM_ASSIGNMENT BEFORE
    INSERT ON TEAM_ASSIGNMENT
     FOR EACH ROW
BEGIN
  SELECT TEAM_ASSIGNMENT_SEQ.NEXTVAL INTO :NEW.ASSIGNMENT_ID FROM DUAL;
END;


CREATE OR REPLACE TRIGGER TRG_EQUIPMENT BEFORE
    INSERT ON EQUIPMENT
     FOR EACH ROW
BEGIN
  SELECT EQUIPMENT_SEQ.NEXTVAL INTO :NEW.EQUIPMENT_ID FROM DUAL;
END;
